---

ldapPasswordReset-main:
    path: /
    defaults: {
        _controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction',
        path: /ldapPasswordReset/login,
        permanent: true
    }
    methods: [GET]

ldapPasswordReset-login:
    path: /login
    defaults: {
        _controller: 'SimpleSAML\Module\ldapPasswordReset\Controller\PasswordReset::login'
    }
    methods: [GET, POST]

ldapPasswordReset-resetPassword:
    path: /resetPassword
    defaults: {
        _controller: 'SimpleSAML\Module\ldapPasswordReset\Controller\PasswordReset::resetPassword'
    }
    methods: [GET, POST]
